import QtQml

// Generated from src/ui/workbenchPalette.json by scripts/generate-workbench-palette.mjs.
QtObject {
  readonly property string bg: "#11120f"
  readonly property string bgDeep: "#0c0d0b"
  readonly property string surface: "#1a1b17"
  readonly property string surface2: "#20211c"
  readonly property string surface3: "#272820"
  readonly property string enamel: "#e8dfca"
  readonly property string enamel2: "#d7cdb7"
  readonly property string enamelInk: "#1d1c17"
  readonly property string border: "#4a493f"
  readonly property string borderSoft: "#37372f"
  readonly property string text: "#eee8da"
  readonly property string muted: "#aaa293"
  readonly property string faint: "#7f7a6f"
  readonly property string track: "#10110f"
  readonly property string ok: "#7fad87"
  readonly property string warn: "#e49350"
  readonly property string crit: "#d9614d"
  readonly property string accent: "#e49350"
  readonly property string instrumentLabel: "#675f50"
  readonly property string sectionLabel: "#6d6557"
  readonly property string enamelCopy: "#625b4f"
  readonly property string dialTrack: "#a49a86"
  readonly property string meterBorder: "#4d4c43"
  readonly property string emptyBorder: "#756e60"
  readonly property string emptyBarBorder: "#716a5d"
  readonly property string emptyBar: "#b9af9b"
  readonly property string controlBorder: "#5c5a4e"
  readonly property string iconShellBorder: "#5a584e"
  readonly property string legendBorder: "#59574c"
  readonly property string danger: "#ed9585"
  readonly property string iconCasing: "#1a1b17"
  readonly property string iconBorder: "#6a6659"
  readonly property string iconTrack: "#403f37"
  readonly property string iconAccent: "#e49350"
}
